server:
  port: 9008
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.60.218.173:3306/gulimall_wms
    username: root
    password: 1234
  application:
    name: gulimall-ware
  cloud:
    nacos:
      discovery:
        server-addr: 123.60.218.173:8848
        namespace: wxf
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml


